### ISSUE TITLE
Crash ( java.lang.NullPointerException at android.view.View.getHardwareLayer )

### ISSUE THREAD

**Issue by forlayo** [flavioarfaria/KenBurnsView#32]
**Device:** Samsung Galaxy SII ( GT-I9100 with Android 4.0.3 )

```
08-24 12:40:36.433    1558-1558/com.x.bla E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at android.view.View.getHardwareLayer(View.java:10318)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2863)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
            at android.view.View.getDisplayList(View.java:10555)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2597)
            at android.view.View.getDisplayList(View.java:10520)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2597)
            at android.view.View.getDisplayList(View.java:10520)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2597)
            at android.view.View.getDisplayList(View.java:10520)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2597)
            at android.view.View.getDisplayList(View.java:10520)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2597)
            at android.view.View.getDisplayList(View.java:10520)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2597)
            at android.view.View.getDisplayList(View.java:10520)
            at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:840)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2049)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1773)
            at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2585)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4507)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by flavioarfaria** [comment]
Sorry, @forlayo, this stack trace is not helpful at all, since it doesn't trace to any KenBurnsView-related code. Can you provide steps to reproduce it?

**Comment by flavioarfaria** [comment]
Closing due to inactivity.
