### ISSUE TITLE
Issue on Samsung galaxy S8

### ISSUE THREAD

**Issue by kishorecs** [flavioarfaria/KenBurnsView#58]
When we use to display an image of 1080x800 webp format image with Ken Burns effect... We are getting the below exception, so far it's has been seen in Galaxy S8 only.

Fatal Exception: java.lang.RuntimeException: Canvas: trying to draw too large(124367104bytes) bitmap.
       at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
       at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
       at android.widget.ImageView.onDraw(ImageView.java:1367)
       at android.view.View.draw(View.java:20352)
       at android.view.View.updateDisplayListIfDirty(View.java:19297)
       at android.view.View.draw(View.java:20075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.updateDisplayListIfDirty(View.java:19288)
       at android.view.View.draw(View.java:20075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
       at android.view.View.updateDisplayListIfDirty(View.java:19288)
       at android.view.View.draw(View.java:20075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.updateDisplayListIfDirty(View.java:19288)
       at android.view.View.draw(View.java:20075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.updateDisplayListIfDirty(View.java:19288)
       at android.view.View.draw(View.java:20075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.updateDisplayListIfDirty(View.java:19288)
       at android.view.View.draw(View.java:20075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.updateDisplayListIfDirty(View.java:19288)
       at android.view.View.draw(View.java:20075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.updateDisplayListIfDirty(View.java:19288)
       at android.view.View.draw(View.java:20075)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
       at android.view.View.draw(View.java:20355)
       at com.android.internal.policy.DecorView.draw(DecorView.java:979)
       at android.view.View.updateDisplayListIfDirty(View.java:19297)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3488)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3275)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2810)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1779)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7810)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:658)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by flavioarfaria** [comment]
Looks like the image is too big to be drawn, although the resolution doesn't suggest so. KenBurnsView doesn't change the actual bitmap size, so this should not be related to KenBurnsView. I'd suggest you to replace the `KenBurnsView` by a regular `ImageView`. You should get the exact same exception.
